### ISSUE TITLE
memory corruption

### ISSUE THREAD

**Issue by winpassuser** [xuy/pyipopt#30]
I'm using Python 3.5.2 x64 on Linux with Numpy 1.11.2 and the latest PyIpopt. The following code returns a segmentation fault, unless the lines in eval_jac_g are commented out. The commented lines do not alter i and/or j as they are already in int64 format, but they do create a copy of the data. I'm suspecting this to be a bug in pyipopt, since Valgrind shows many errors related to invalid reads/writes.
```python
import numpy as np
import pyipopt

A = np.matrix([[1.0, 0, 1], [2,3,1]])
p = np.transpose(np.matrix([[0.0],[10]]))
I,J = A.shape

nvar = J
ncon = I

x_L = np.zeros((nvar), dtype=float)
x_U = np.ones((nvar), dtype=float) * float('inf')

g_L = np.zeros(ncon)
g_U = np.ones((ncon), dtype=float) * 10.0

def eval_f(x):
  return 0.0

def eval_grad_f(x):
  return np.array([0, 0, 0], np.float_);

def eval_g(x):
  return np.squeeze(np.asarray(np.dot(A, x)))

nnzj = np.count_nonzero(A)
def eval_jac_g(x, flag):
  if flag:
    i,j = np.nonzero(A)
#    i = i.astype(np.int64)
#    j = j.astype(np.int64)
    return i,j
  else:
    return np.squeeze(np.asarray(A[np.nonzero(A)], dtype = float))

nnzh = np.count_nonzero(A)

nlp = pyipopt.create(nvar, x_L, x_U, ncon, g_L, g_U, nnzj, nnzh, eval_f, eval_grad_f, eval_g, eval_jac_g)

x0 = np.ones(nvar, dtype = float)
x, zl, zu, constraint_multipliers, obj, status = nlp.solve(x0)
```

**Comment by xuy** [comment]
Hey @winpassuser , I *suspect* that you cannot really use int64 as the return value for Jacobian matrix (by IPOPT's spec it should be float anyway). I think pyIPOPT assumes a float numpy arrary there, so int64 probably is not the right number of bytes for return result. Did you try dtype=float instead?

**Comment by xuy** [comment]
I think I pin-pointed the root cause. Long story short: always return a fresh ndarray from these call back functions, don't rely on references. 

np.nonzero(A) returns a reference to the nonzero field of A, which to lower level C library is just a pointer. Because of that, pyIPOPT releases the pointer after the first jacobian evaluation. Thus the second one will have a segfault (null pointer to nonzero). The astype call constructs a new array whenever the callback is invoked, which will be owned and released by pyIPOPT safely.
